spring:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:entretien
    username: user
    password: password

server:
  port: 8081

  flyway:
    table: schema_version
